### ISSUE TITLE
Is there anyway to pass custom headers ?

### ISSUE THREAD

**Issue by didierfranc** [grpc-ecosystem/protoc-gen-grpc-gateway-ts#13]
It is useful to pass a header like `Authorization` to the query, I can't find a way to pass it

**Comment by abatilo** [comment]
@didierfranc did you find your answer?

**Comment by atreya2011** [comment]
@abatilo Given a service definition like this:

```ts
  static HTTPPostWithStarBodyPath(req: HttpPostRequest, initReq?: fm.InitReq): Promise<HttpPostResponse> {
    return fm.fetchReq<HttpPostRequest, HttpPostResponse>(`/post/${req["a"]}/${req["c"]}`, {...initReq, method: "POST", body: JSON.stringify(req)})
  }
```


Just pass the headers as fetch options like this as the second parameter (`initReq`)

```js
    pathPrefix: `endpointURL`,
    headers: {
      Authorization: `Bearer token`,
    },
```

**Comment by abatilo** [comment]
Ah, that makes sense. It almost looks like initReq are just regular params for a fetch request!

Thank you very much.

**Comment by atreya2011** [comment]
@abatilo 
Yes you are correct, initReq just extends the regular params for a fetch request and adds `pathPrefix` for appending the endpoint URL prefix 👍🏼

**Comment by didierfranc** [comment]
What's your thought about setting those params one time (in a constructor) instead of passing it to every method?

**Comment by didierfranc** [comment]
What's your thought about setting those params one time (in a constructor) instead of passing them to every method call?

**Comment by atreya2011** [comment]
Yes, I did gave that idea some consideration. Let's take React as an example and assume that you have two components: one calling a `ListUsers` RPC and another calling an `AddUser` RPC. In each of those components, you have to instantiate the `UserService` class and pass the params to a constructor. So you are technically passing the params twice. And this is the same as passing the params to every method call.

**Comment by abatilo** [comment]
> Yes, I did gave that idea some consideration. Let's take React as an example and assume that you have two components: one calling a `ListUsers` RPC and another calling an `AddUser` RPC. In each of those components, you have to instantiate the `UserService` class and pass the params to a constructor. So you are technically passing the params twice (once in each component). And this is the same as passing the params to every method call. 

There are ways around that though. If you create a ContextProvider for the client, then you can have multiple components use the same instance.

**Comment by atreya2011** [comment]
I see what you mean. Perhaps you can raise this as a separate issue and check the feasibility of making a PR where you can pass the params to a constructor.
