### ISSUE TITLE
Handling errors

### ISSUE THREAD

**Issue by remko** [grpc-ecosystem/protoc-gen-grpc-gateway-ts#15]
The fetch function seems to ignore the .ok status of the fetch response. This means that if there is a gRPC error, data is returned of the error type instead of the declared response type.

Shouldn’t the fetch function throw in case of http errors (I.e. if .ok is false), so the client can catch errors? (And so there is no typing inconsistency)

**Comment by lyonlai** [comment]
gRPC error returned from `grpc-gateway` is still http 200 but with error object as JSON returned iirc.

**Comment by atreya2011** [comment]
@remko You could just check the error object instead.

**Comment by remko** [comment]
@lyonlai No,`grpc-gateway` [maps gRPC codes to HTTP](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/runtime/errors.go#L37)

    < HTTP/1.1 401 Unauthorized
    < Content-Type: application/json; charset=utf-8
    < Date: Tue, 18 May 2021 05:46:57 GMT
    < Content-Length: 40
    < 
    {"status":401,"message":"Unauthorized"}

**Comment by remko** [comment]
@atreya2011 There's no unambiguous way to check for an error object at that level. I would have to check for the presence of `status` and `message` properties, which could exist on a regular object too (e.g. a chat service presence object)

Moreover, I would need to manually do this check for every call, or at least manually wrap every call, which is tedious.

**Comment by lyonlai** [comment]
hmm. I see, that make sense. @remko do you have something already and you wanted to contribute?

**Comment by remko** [comment]
@lyonlai I don't, but I should be able to easily do, just wanted to check up front. I will do the changes and verify it with my use case, and send a PR.

**Comment by lyonlai** [comment]
awesome, expecting it.
