### ISSUE TITLE
Send bytes in a message

### ISSUE THREAD

**Issue by Unix4ever** [grpc-ecosystem/protoc-gen-grpc-gateway-ts#22]
If a protocol has messages that have `bytes` type, generator outputs them as `Uint8Array`, which is not properly encoded by simple `JSON.stringify` call. See:
![image](https://user-images.githubusercontent.com/830532/124839852-47567600-df92-11eb-8a3e-66593ae71f5e.png)

I guess it should be converted to base64 encoded string instead.
For that case stringify calls should either contain `replacer` or `Uint8Array` should have `toJSON` definition.

**Comment by lyonlai** [comment]
Thanks for reporting the issue. I looked it up in golang's json package and there are base64 encoding/decoding going on. I'll start putting some comments in the PR.

https://pkg.go.dev/encoding/json#Marshal

**Comment by kabece** [comment]
The fix works for the request body but if there are bytes in the query params they're being removed by `flattenRequestPayload`.

Changing the function to:

```
function flattenRequestPayload<T extends RequestPayload>(
  requestPayload: T,
  path: string = ''
): FlattenedRequestPayload {
  return Object.keys(requestPayload).reduce((acc: T, key: string): T => {
    const value = requestPayload[key];
    const newPath = path ? [path, key].join('.') : key;

    const isNonEmptyPrimitiveArray =
      Array.isArray(value) &&
      value.every(v => isPrimitive(v)) &&
      value.length > 0;

    const isNonZeroValuePrimitive =
      isPrimitive(value) && !isZeroValuePrimitive(value as Primitive);

    let objectToMerge = {};

    if (isPlainObject(value)) {
      objectToMerge = flattenRequestPayload(value as RequestPayload, newPath);
    } else if (isNonZeroValuePrimitive || isNonEmptyPrimitiveArray) {
      objectToMerge = { [newPath]: value };
    } else if (value && value.constructor === Uint8Array) {
      objectToMerge = { [newPath]: b64Encode(value, 0, value.length) };
    }

    return { ...acc, ...objectToMerge };
  }, {} as T) as FlattenedRequestPayload;
}
```

seems to fix the issue.
