### ISSUE TITLE
Windows - Back-slashes in generated import statements

### ISSUE THREAD

**Issue by Drabuna** [grpc-ecosystem/protoc-gen-grpc-gateway-ts#36]
When using this library on Windows you get generated TS with back-slashes instead of forward-slashes in import statements. Obviously, TS is not very happy about it, and it doesn't work unless you replace all the slashes. Here's an example:

```
import * as fm from ".\fetch.pb"
import * as GoogleApiHttpbody from ".\google\api\httpbody.pb"
import * as GoogleProtobufEmpty from ".\google\protobuf\empty.pb"
import * as GoogleProtobufTimestamp from ".\google\protobuf\timestamp.pb"
```

**Comment by asjdf** [comment]
This issue seems to have not been fixed yet?
