### ISSUE TITLE
Handling well-known types

### ISSUE THREAD

**Issue by atreya2011** [grpc-ecosystem/protoc-gen-grpc-gateway-ts#4]
Given the following proto message:

```
syntax = "proto3";

import "google/protobuf/timestamp.proto";
import "google/protobuf/any.proto";

message User {
  string                    id       = 1;
  string                    name     = 2;
  google.protobuf.Timestamp my_field = 3;
}

// https://developers.google.com/protocol-buffers/docs/proto3#any
message ErrorStatus {
  string   message                     = 1;
  repeated google.protobuf.Any details = 2;
}
```

The following TypeScript is being generated which throws a type error because neither `timestamp.pb.ts` nor `any.pb` exist.

```ts
/*
* This file is a generated Typescript file for GRPC Gateway, DO NOT MODIFY
*/

import * as GoogleProtobufAny from "../google/protobuf/any.pb"
import * as GoogleProtobufTimestamp from "../google/protobuf/timestamp.pb"

export type User = {
  id?: string
  name?: string
  myField?: GoogleProtobufTimestamp.Timestamp
}

export type ErrorStatus = {
  message?: string
  details?: GoogleProtobufAny.Any[]
}
```

Please let me know if I am missing any steps in the generation process 🙏🏼 
I used the following command to generate the above TypeScript file.

`protoc -I. --grpc-gateway-ts_out=. --grpc-gateway-ts_opt logtostderr=true --grpc-gateway-ts_opt loglevel=debug ./proto/example.proto`

**Comment by atreya2011** [comment]
I added support for handling the following well-known types and have confirmed it working locally.

1. `google.protobuf.Empty` => corresponding TypeScript type: `Record<never, never>`
2. `google.protobuf.Any` => corresponding TypeScript type: `any`
3. `google.protobuf.Timestamp` => corresponding TypeScript type: `Date`

Is it ok to make a PR?

**Comment by lyonlai** [comment]
```
The following TypeScript is being generated which throws a type error because neither timestamp.pb.ts nor any.pb exist.
```

^^ you need to run the protoc-gen-grpc-gateway-ts on `timestamp.pb.ts` and `any.pb`. That's how we did it.

**Comment by atreya2011** [comment]
Ah I see... Is the following fix acceptable as a PR?

https://github.com/atreya2011/protoc-gen-grpc-gateway-ts/commit/a1e3d5c3381788a3f673174b4c3d17b0476bc0e3

**Comment by lyonlai** [comment]
Generate typescript for the depending proto files works out nicely and it is a natural requirement like all other protoc plugins. So I don't think making a special case here make sense.

**Comment by atreya2011** [comment]
Thanks for your reply and I understand your reasoning. However, it becomes difficult to use this with a tool like buf and generate files for both client and server simultaneously. 

https://buf.build/

**Comment by atreya2011** [comment]
Ok I understand. Thank you for your kind response 🙇🏼

**Comment by lixin9311** [comment]
> ```
> The following TypeScript is being generated which throws a type error because neither timestamp.pb.ts nor any.pb exist.
> ```
> 
> ^^ you need to run the protoc-gen-grpc-gateway-ts on `timestamp.pb.ts` and `any.pb`. That's how we did it.

Hi, if we run the protoc-gen-grpc-gateway-ts on `timestamp.pb`, we will get the definition of the underlying timestamp.

```
// example message
export type Message = {
  value?: string
  waitPeriod?: GoogleProtobufDuration.Duration
  ts?: GoogleProtobufTimestamp.Timestamp
}
// the definition of GoogleProtobufTimestamp.Timestamp
export type Timestamp = {
  seconds?: string
  nanos?: number
}
```

Which will be rejected by grpc-gateway.
The correct json mapping of the timestamp is a datetime in RFC3339(nano) format, which can be fulfilled by the default behavior of JSON.stringify a Date object in JavaScript.

I think we still need to set up exception rules for parsing those WKTs, at least for Timestamp and Duration.
https://developers.google.com/protocol-buffers/docs/proto3#json

**Comment by atreya2011** [comment]
@lixin9311 Since this issue is closed, you can reference this and open a new issue 🙏🏼
