### ISSUE TITLE
renderURL does not use lowerCamelCase field names

### ISSUE THREAD

**Issue by atreya2011** [grpc-ecosystem/protoc-gen-grpc-gateway-ts#5]
Given a proto file with the following annotation and fieldname for `GetUserRequest`:

```proto
service UserService {
  rpc GetUser(GetUserRequest) returns (GetUserResponse) {
    option (google.api.http) = {
      get: "/api/v1/user/{user_id}"
    };
  }
}

message GetUserRequest {
  string user_id = 1;
}

message GetUserResponse {
  User user = 1;
}

message User {
  string id   = 1;
  string name = 2;
}
```

generates the following TypeScript:

```ts
/*
* This file is a generated Typescript file for GRPC Gateway, DO NOT MODIFY
*/

export type GetUserRequest = {
  userId?: string
}

export type GetUserResponse = {
  user?: User
}

export type User = {
  id?: string
  name?: string
}

export class UserService {
  static GetUser(req: GetUserRequest, initReq?: fm.InitReq): Promise<GetUserResponse> {
    return fm.fetchReq<GetUserRequest, GetUserResponse>(`/api/v1/user/${req["user_id"]}`, {...initReq, method: "GET"})
  }
}
```

Which throws a type error because of `/api/v1/user/${req["user_id"]}` as `user_id` does not exist in the generated type definition for `GetUserRequest`

I have fixed this locally. Is it ok to create a PR?

**Comment by lyonlai** [comment]
hmm. there are supposed to be tests covering it but not sure how it failed, which concerns me. I'll take a look at this. Thanks for reporting. will let you know soon @atreya2011

**Comment by atreya2011** [comment]
Likewise, thank you for making this excellent plugin! 🙇🏼 I have fixed this locally, let me know if it is ok to create a PR?

https://github.com/atreya2011/protoc-gen-grpc-gateway-ts/commit/b8d327e8721d13c3eed2814a99c9df2d89f73250

**Comment by lyonlai** [comment]
Thanks for being so passionate about this project. The fix itself is easy but I would like to adjust the test to catch this problem as well. That's why I prefer to take a look and let you know soon @atreya2011 

I see the support for `HTTP Patch` is in the PR as well. Much appreciate the contribution but I think it would be better in it's own PR.

**Comment by atreya2011** [comment]
Thank you very much! I will make a different PR for the HTTP Patch fix.

And this is just the plugin I was looking for because I have the same pain points that you mentioned in this blog post 👇🏼 
https://cashapp.github.io/2021-03-26/protoc-gen-grpc-gateway-ts-clean-idiomatic-typescript-for-grpc-gateway
